# Generated by Django 4.0.4 on 2022-05-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='작성자')),
                ('category', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('User', 'User'), ('Etc', 'Etc')], default='Python', max_length=20, verbose_name='종류')),
                ('content', models.TextField(verbose_name='내용')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('writer', models.CharField(max_length=20, verbose_name='작성자')),
                ('category', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('User', 'User'), ('Etc', 'Etc')], max_length=20, verbose_name='종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('number', models.TextField(verbose_name='전화번호')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
            ],
        ),
    ]
